insert into haltestelle (name) values 
("Mettmannstrasse"),
("Salamiweg"),
("Berliner Platz"),
("Klabauterplatz"),
("Theater"),
("Paradeplatz"),
("Eierweg"),
("Baumstrasse"),
("Völmederstrasse"),
("Bahnhof"),
("Igelweg"),
("Faultierplatz"),
("Nacktmullstrasse"),
("Kino"),
("Westring"),
("Alsterwall"),
("Landhaus Günther"),
("Stadtpark"),
("Alter Kirchweg"),
("Schorlemerstrasse"),
("Am Rabbenfittich"),
("Vernerstrasse"),
("Rostockallee"),
("Schwerinstrasse"),
("Zum Ausblick"),
("Herrengasse"),
("Baumwall"),
("Berliner Tor"),
("Lübecker Strasse"),
("Hamburger Strasse"),
("Veddel"),
("Anckerstrasse"),
("Wohlersallee"),
("Kleingarten"),
("Potterweg"),
("Merlinplatz"),
("Tolkienweg"),
("Bilbohaus"),
("Bombadilplatz"),
("Gandalfstrasse"),
("Streicherweg"),
("Isengarten");
